// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5MIFDsgmsJaZFPF-wbQtxcKulUJjLpOY',
    appId: '1:776774578845:web:14b3b616b1851638e4da74',
    messagingSenderId: '776774578845',
    projectId: 'elderly-people-app-2d572',
    authDomain: 'elderly-people-app-2d572.firebaseapp.com',
    storageBucket: 'elderly-people-app-2d572.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhm53JeVleW8uPe0Eq78B_oepr3GYQDOo',
    appId: '1:776774578845:android:330a5878abc3edcbe4da74',
    messagingSenderId: '776774578845',
    projectId: 'elderly-people-app-2d572',
    storageBucket: 'elderly-people-app-2d572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcbrUOIFKTbqocHjhrK6fNRdIAggCmJ-A',
    appId: '1:776774578845:ios:c9737a64fd421609e4da74',
    messagingSenderId: '776774578845',
    projectId: 'elderly-people-app-2d572',
    storageBucket: 'elderly-people-app-2d572.firebasestorage.app',
    iosBundleId: 'com.example.elderlyPrototypeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcbrUOIFKTbqocHjhrK6fNRdIAggCmJ-A',
    appId: '1:776774578845:ios:c9737a64fd421609e4da74',
    messagingSenderId: '776774578845',
    projectId: 'elderly-people-app-2d572',
    storageBucket: 'elderly-people-app-2d572.firebasestorage.app',
    iosBundleId: 'com.example.elderlyPrototypeApp',
  );
}
